// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/keshablive/quester/internal/models"

	uuid "github.com/google/uuid"
)

// BadgeRepository is an autogenerated mock type for the BadgeRepository type
type BadgeRepository struct {
	mock.Mock
}

// AwardBadgeToUser provides a mock function with given fields: ctx, userBadge
func (_m *BadgeRepository) AwardBadgeToUser(ctx context.Context, userBadge *models.UserBadge) error {
	ret := _m.Called(ctx, userBadge)

	if len(ret) == 0 {
		panic("no return value specified for AwardBadgeToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserBadge) error); ok {
		r0 = rf(ctx, userBadge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, badge
func (_m *BadgeRepository) Create(ctx context.Context, badge *models.Badge) error {
	ret := _m.Called(ctx, badge)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Badge) error); ok {
		r0 = rf(ctx, badge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tenantID, badgeID
func (_m *BadgeRepository) Delete(ctx context.Context, tenantID uuid.UUID, badgeID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, badgeID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, badgeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tenantID
func (_m *BadgeRepository) FindAll(ctx context.Context, tenantID uuid.UUID) ([]models.Badge, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Badge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Badge, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Badge); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Badge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tenantID, badgeID
func (_m *BadgeRepository) FindByID(ctx context.Context, tenantID uuid.UUID, badgeID uuid.UUID) (*models.Badge, error) {
	ret := _m.Called(ctx, tenantID, badgeID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Badge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Badge, error)); ok {
		return rf(ctx, tenantID, badgeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Badge); ok {
		r0 = rf(ctx, tenantID, badgeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Badge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, badgeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBadgeEarnCount provides a mock function with given fields: ctx, tenantID, badgeID
func (_m *BadgeRepository) GetBadgeEarnCount(ctx context.Context, tenantID uuid.UUID, badgeID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, tenantID, badgeID)

	if len(ret) == 0 {
		panic("no return value specified for GetBadgeEarnCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int64, error)); ok {
		return rf(ctx, tenantID, badgeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r0 = rf(ctx, tenantID, badgeID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, badgeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBadgesByType provides a mock function with given fields: ctx, tenantID, badgeType
func (_m *BadgeRepository) GetBadgesByType(ctx context.Context, tenantID uuid.UUID, badgeType string) ([]models.Badge, error) {
	ret := _m.Called(ctx, tenantID, badgeType)

	if len(ret) == 0 {
		panic("no return value specified for GetBadgesByType")
	}

	var r0 []models.Badge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]models.Badge, error)); ok {
		return rf(ctx, tenantID, badgeType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []models.Badge); ok {
		r0 = rf(ctx, tenantID, badgeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Badge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tenantID, badgeType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBadges provides a mock function with given fields: ctx, tenantID, userID
func (_m *BadgeRepository) GetUserBadges(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]models.UserBadge, error) {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBadges")
	}

	var r0 []models.UserBadge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.UserBadge, error)); ok {
		return rf(ctx, tenantID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.UserBadge); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserBadge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasUserEarnedBadge provides a mock function with given fields: ctx, tenantID, userID, badgeID
func (_m *BadgeRepository) HasUserEarnedBadge(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, badgeID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, tenantID, userID, badgeID)

	if len(ret) == 0 {
		panic("no return value specified for HasUserEarnedBadge")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, tenantID, userID, badgeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, tenantID, userID, badgeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID, badgeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeBadgeFromUser provides a mock function with given fields: ctx, tenantID, userID, badgeID
func (_m *BadgeRepository) RevokeBadgeFromUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, badgeID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, userID, badgeID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeBadgeFromUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, userID, badgeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, badge
func (_m *BadgeRepository) Update(ctx context.Context, badge *models.Badge) error {
	ret := _m.Called(ctx, badge)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Badge) error); ok {
		r0 = rf(ctx, badge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBadgeRepository creates a new instance of BadgeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBadgeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BadgeRepository {
	mock := &BadgeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
