// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/keshablive/quester/internal/models"

	uuid "github.com/google/uuid"
)

// LeaderboardRepository is an autogenerated mock type for the LeaderboardRepository type
type LeaderboardRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, entry
func (_m *LeaderboardRepository) Create(ctx context.Context, entry *models.Leaderboard) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Leaderboard) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tenantID, entryID
func (_m *LeaderboardRepository) Delete(ctx context.Context, tenantID uuid.UUID, entryID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, entryID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, entryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tenantID, limit, offset
func (_m *LeaderboardRepository) FindAll(ctx context.Context, tenantID uuid.UUID, limit int, offset int) ([]models.Leaderboard, int64, error) {
	ret := _m.Called(ctx, tenantID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Leaderboard
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]models.Leaderboard, int64, error)); ok {
		return rf(ctx, tenantID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []models.Leaderboard); ok {
		r0 = rf(ctx, tenantID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Leaderboard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, tenantID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, tenantID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, tenantID, entryID
func (_m *LeaderboardRepository) FindByID(ctx context.Context, tenantID uuid.UUID, entryID uuid.UUID) (*models.Leaderboard, error) {
	ret := _m.Called(ctx, tenantID, entryID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Leaderboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Leaderboard, error)); ok {
		return rf(ctx, tenantID, entryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Leaderboard); ok {
		r0 = rf(ctx, tenantID, entryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Leaderboard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, entryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeaderboardByPeriod provides a mock function with given fields: ctx, tenantID, period, limit
func (_m *LeaderboardRepository) GetLeaderboardByPeriod(ctx context.Context, tenantID uuid.UUID, period string, limit int) ([]models.Leaderboard, error) {
	ret := _m.Called(ctx, tenantID, period, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardByPeriod")
	}

	var r0 []models.Leaderboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) ([]models.Leaderboard, error)); ok {
		return rf(ctx, tenantID, period, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) []models.Leaderboard); ok {
		r0 = rf(ctx, tenantID, period, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Leaderboard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = rf(ctx, tenantID, period, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopPlayers provides a mock function with given fields: ctx, tenantID, limit
func (_m *LeaderboardRepository) GetTopPlayers(ctx context.Context, tenantID uuid.UUID, limit int) ([]models.Leaderboard, error) {
	ret := _m.Called(ctx, tenantID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopPlayers")
	}

	var r0 []models.Leaderboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]models.Leaderboard, error)); ok {
		return rf(ctx, tenantID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []models.Leaderboard); ok {
		r0 = rf(ctx, tenantID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Leaderboard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, tenantID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserLeaderboardEntry provides a mock function with given fields: ctx, tenantID, userID
func (_m *LeaderboardRepository) GetUserLeaderboardEntry(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (*models.Leaderboard, error) {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLeaderboardEntry")
	}

	var r0 *models.Leaderboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Leaderboard, error)); ok {
		return rf(ctx, tenantID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Leaderboard); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Leaderboard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRank provides a mock function with given fields: ctx, tenantID, userID
func (_m *LeaderboardRepository) GetUserRank(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRank")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int64, error)); ok {
		return rf(ctx, tenantID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetLeaderboard provides a mock function with given fields: ctx, tenantID, period
func (_m *LeaderboardRepository) ResetLeaderboard(ctx context.Context, tenantID uuid.UUID, period string) error {
	ret := _m.Called(ctx, tenantID, period)

	if len(ret) == 0 {
		panic("no return value specified for ResetLeaderboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tenantID, period)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, entry
func (_m *LeaderboardRepository) Update(ctx context.Context, entry *models.Leaderboard) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Leaderboard) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserScore provides a mock function with given fields: ctx, tenantID, userID, score
func (_m *LeaderboardRepository) UpdateUserScore(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, score int) error {
	ret := _m.Called(ctx, tenantID, userID, score)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserScore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, tenantID, userID, score)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLeaderboardRepository creates a new instance of LeaderboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaderboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaderboardRepository {
	mock := &LeaderboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
