// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/keshablive/quester/internal/models"

	uuid "github.com/google/uuid"
)

// PropertyRepository is an autogenerated mock type for the PropertyRepository type
type PropertyRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, property
func (_m *PropertyRepository) Create(ctx context.Context, property *models.Property) error {
	ret := _m.Called(ctx, property)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Property) error); ok {
		r0 = rf(ctx, property)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tenantID, propertyID
func (_m *PropertyRepository) Delete(ctx context.Context, tenantID uuid.UUID, propertyID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, propertyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, propertyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tenantID, limit, offset
func (_m *PropertyRepository) FindAll(ctx context.Context, tenantID uuid.UUID, limit int, offset int) ([]models.Property, int64, error) {
	ret := _m.Called(ctx, tenantID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Property
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]models.Property, int64, error)); ok {
		return rf(ctx, tenantID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []models.Property); ok {
		r0 = rf(ctx, tenantID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Property)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, tenantID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, tenantID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, tenantID, propertyID
func (_m *PropertyRepository) FindByID(ctx context.Context, tenantID uuid.UUID, propertyID uuid.UUID) (*models.Property, error) {
	ret := _m.Called(ctx, tenantID, propertyID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Property
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Property, error)); ok {
		return rf(ctx, tenantID, propertyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Property); ok {
		r0 = rf(ctx, tenantID, propertyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Property)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, propertyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPropertiesByOwnerID provides a mock function with given fields: ctx, tenantID, ownerID
func (_m *PropertyRepository) GetPropertiesByOwnerID(ctx context.Context, tenantID uuid.UUID, ownerID uuid.UUID) ([]models.Property, error) {
	ret := _m.Called(ctx, tenantID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPropertiesByOwnerID")
	}

	var r0 []models.Property
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.Property, error)); ok {
		return rf(ctx, tenantID, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.Property); ok {
		r0 = rf(ctx, tenantID, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Property)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPropertiesByStatus provides a mock function with given fields: ctx, tenantID, status
func (_m *PropertyRepository) GetPropertiesByStatus(ctx context.Context, tenantID uuid.UUID, status string) ([]models.Property, error) {
	ret := _m.Called(ctx, tenantID, status)

	if len(ret) == 0 {
		panic("no return value specified for GetPropertiesByStatus")
	}

	var r0 []models.Property
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]models.Property, error)); ok {
		return rf(ctx, tenantID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []models.Property); ok {
		r0 = rf(ctx, tenantID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Property)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tenantID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchNearby provides a mock function with given fields: ctx, tenantID, latitude, longitude, radiusMeters
func (_m *PropertyRepository) SearchNearby(ctx context.Context, tenantID uuid.UUID, latitude float64, longitude float64, radiusMeters float64) ([]models.Property, error) {
	ret := _m.Called(ctx, tenantID, latitude, longitude, radiusMeters)

	if len(ret) == 0 {
		panic("no return value specified for SearchNearby")
	}

	var r0 []models.Property
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, float64, float64) ([]models.Property, error)); ok {
		return rf(ctx, tenantID, latitude, longitude, radiusMeters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, float64, float64) []models.Property); ok {
		r0 = rf(ctx, tenantID, latitude, longitude, radiusMeters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Property)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, float64, float64, float64) error); ok {
		r1 = rf(ctx, tenantID, latitude, longitude, radiusMeters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, property
func (_m *PropertyRepository) Update(ctx context.Context, property *models.Property) error {
	ret := _m.Called(ctx, property)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Property) error); ok {
		r0 = rf(ctx, property)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePropertyLocation provides a mock function with given fields: ctx, propertyID, latitude, longitude
func (_m *PropertyRepository) UpdatePropertyLocation(ctx context.Context, propertyID uuid.UUID, latitude float64, longitude float64) error {
	ret := _m.Called(ctx, propertyID, latitude, longitude)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePropertyLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, float64) error); ok {
		r0 = rf(ctx, propertyID, latitude, longitude)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPropertyRepository creates a new instance of PropertyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPropertyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PropertyRepository {
	mock := &PropertyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
