// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/keshablive/quester/internal/models"

	uuid "github.com/google/uuid"
)

// QuestRepository is an autogenerated mock type for the QuestRepository type
type QuestRepository struct {
	mock.Mock
}

// CountQuestsByStatus provides a mock function with given fields: ctx, tenantID, status
func (_m *QuestRepository) CountQuestsByStatus(ctx context.Context, tenantID uuid.UUID, status string) (int64, error) {
	ret := _m.Called(ctx, tenantID, status)

	if len(ret) == 0 {
		panic("no return value specified for CountQuestsByStatus")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (int64, error)); ok {
		return rf(ctx, tenantID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) int64); ok {
		r0 = rf(ctx, tenantID, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tenantID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, quest
func (_m *QuestRepository) Create(ctx context.Context, quest *models.Quest) error {
	ret := _m.Called(ctx, quest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Quest) error); ok {
		r0 = rf(ctx, quest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tenantID, questID
func (_m *QuestRepository) Delete(ctx context.Context, tenantID uuid.UUID, questID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, questID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, questID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tenantID, filters
func (_m *QuestRepository) FindAll(ctx context.Context, tenantID uuid.UUID, filters map[string]interface{}) ([]models.Quest, error) {
	ret := _m.Called(ctx, tenantID, filters)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Quest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]interface{}) ([]models.Quest, error)); ok {
		return rf(ctx, tenantID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]interface{}) []models.Quest); ok {
		r0 = rf(ctx, tenantID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Quest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]interface{}) error); ok {
		r1 = rf(ctx, tenantID, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tenantID, questID
func (_m *QuestRepository) FindByID(ctx context.Context, tenantID uuid.UUID, questID uuid.UUID) (*models.Quest, error) {
	ret := _m.Called(ctx, tenantID, questID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Quest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Quest, error)); ok {
		return rf(ctx, tenantID, questID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Quest); ok {
		r0 = rf(ctx, tenantID, questID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Quest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, questID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveQuests provides a mock function with given fields: ctx, tenantID
func (_m *QuestRepository) GetActiveQuests(ctx context.Context, tenantID uuid.UUID) ([]models.Quest, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveQuests")
	}

	var r0 []models.Quest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Quest, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Quest); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Quest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuestsByBadgeID provides a mock function with given fields: ctx, tenantID, badgeID
func (_m *QuestRepository) GetQuestsByBadgeID(ctx context.Context, tenantID uuid.UUID, badgeID uuid.UUID) ([]models.Quest, error) {
	ret := _m.Called(ctx, tenantID, badgeID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestsByBadgeID")
	}

	var r0 []models.Quest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.Quest, error)); ok {
		return rf(ctx, tenantID, badgeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.Quest); ok {
		r0 = rf(ctx, tenantID, badgeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Quest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, badgeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuestsByCreatorID provides a mock function with given fields: ctx, tenantID, creatorID
func (_m *QuestRepository) GetQuestsByCreatorID(ctx context.Context, tenantID uuid.UUID, creatorID uuid.UUID) ([]models.Quest, error) {
	ret := _m.Called(ctx, tenantID, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestsByCreatorID")
	}

	var r0 []models.Quest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.Quest, error)); ok {
		return rf(ctx, tenantID, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.Quest); ok {
		r0 = rf(ctx, tenantID, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Quest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuestsByStatus provides a mock function with given fields: ctx, tenantID, status
func (_m *QuestRepository) GetQuestsByStatus(ctx context.Context, tenantID uuid.UUID, status string) ([]models.Quest, error) {
	ret := _m.Called(ctx, tenantID, status)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestsByStatus")
	}

	var r0 []models.Quest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]models.Quest, error)); ok {
		return rf(ctx, tenantID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []models.Quest); ok {
		r0 = rf(ctx, tenantID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Quest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tenantID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, quest
func (_m *QuestRepository) Update(ctx context.Context, quest *models.Quest) error {
	ret := _m.Called(ctx, quest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Quest) error); ok {
		r0 = rf(ctx, quest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuestRepository creates a new instance of QuestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestRepository {
	mock := &QuestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
