// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/keshablive/quester/internal/models"

	uuid "github.com/google/uuid"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, transaction
func (_m *TransactionRepository) Create(ctx context.Context, transaction *models.Transaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tenantID, transactionID
func (_m *TransactionRepository) Delete(ctx context.Context, tenantID uuid.UUID, transactionID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, transactionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tenantID, filters
func (_m *TransactionRepository) FindAll(ctx context.Context, tenantID uuid.UUID, filters map[string]interface{}) ([]models.Transaction, error) {
	ret := _m.Called(ctx, tenantID, filters)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]interface{}) ([]models.Transaction, error)); ok {
		return rf(ctx, tenantID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]interface{}) []models.Transaction); ok {
		r0 = rf(ctx, tenantID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]interface{}) error); ok {
		r1 = rf(ctx, tenantID, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tenantID, transactionID
func (_m *TransactionRepository) FindByID(ctx context.Context, tenantID uuid.UUID, transactionID uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(ctx, tenantID, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Transaction, error)); ok {
		return rf(ctx, tenantID, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Transaction); ok {
		r0 = rf(ctx, tenantID, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingEscrowTransactions provides a mock function with given fields: ctx, tenantID
func (_m *TransactionRepository) GetPendingEscrowTransactions(ctx context.Context, tenantID uuid.UUID) ([]models.Transaction, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingEscrowTransactions")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Transaction, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Transaction); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByDateRange provides a mock function with given fields: ctx, tenantID, startDate, endDate
func (_m *TransactionRepository) GetTransactionsByDateRange(ctx context.Context, tenantID uuid.UUID, startDate string, endDate string) ([]models.Transaction, error) {
	ret := _m.Called(ctx, tenantID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByDateRange")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) ([]models.Transaction, error)); ok {
		return rf(ctx, tenantID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) []models.Transaction); ok {
		r0 = rf(ctx, tenantID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, tenantID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByStatus provides a mock function with given fields: ctx, tenantID, status
func (_m *TransactionRepository) GetTransactionsByStatus(ctx context.Context, tenantID uuid.UUID, status string) ([]models.Transaction, error) {
	ret := _m.Called(ctx, tenantID, status)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByStatus")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]models.Transaction, error)); ok {
		return rf(ctx, tenantID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []models.Transaction); ok {
		r0 = rf(ctx, tenantID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tenantID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByUserID provides a mock function with given fields: ctx, tenantID, userID
func (_m *TransactionRepository) GetTransactionsByUserID(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]models.Transaction, error) {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByUserID")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.Transaction, error)); ok {
		return rf(ctx, tenantID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.Transaction); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBalance provides a mock function with given fields: ctx, tenantID, userID
func (_m *TransactionRepository) GetUserBalance(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (float64, error)); ok {
		return rf(ctx, tenantID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) float64); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, transaction
func (_m *TransactionRepository) Update(ctx context.Context, transaction *models.Transaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionStatus provides a mock function with given fields: ctx, transactionID, status
func (_m *TransactionRepository) UpdateTransactionStatus(ctx context.Context, transactionID uuid.UUID, status string) error {
	ret := _m.Called(ctx, transactionID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, transactionID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
