#!/bin/bash

# T207: Performance Profiler Manual Test Guide
# Tests P1 screens (feed, profile, courses, marketplace) for 60 FPS performance

set -e

echo "=============================================="
echo "T207: Performance Profiler Manual Test Guide"
echo "=============================================="
echo ""
echo "This script provides instructions for manual performance testing"
echo "of P1 screens using React Native performance profiler."
echo ""
echo "Target: 60 FPS maintained during scrolling"
echo "Success Criteria: SC-006 - All screens render in <1s on mid-range devices"
echo ""

# P1 screens to test
P1_SCREENS=(
  "feed:(tabs)/feed.tsx"
  "profile:profile.tsx"
  "courses:(tabs)/courses.tsx"
  "marketplace:(tabs)/marketplace.tsx"
)

echo "=============================================="
echo "STEP 1: Start React Native Development Server"
echo "=============================================="
echo ""
echo "Run in terminal:"
echo "  cd /d/quester/client"
echo "  npm start"
echo ""
echo "Wait for Metro bundler to be ready."
echo ""

echo "=============================================="
echo "STEP 2: Enable Performance Monitor"
echo "=============================================="
echo ""
echo "In React Native app (iOS/Android):"
echo "  1. Shake device or press Cmd+D (iOS) / Cmd+M (Android)"
echo "  2. Select 'Show Performance Monitor'"
echo "  3. You should see FPS counter overlay"
echo ""

echo "=============================================="
echo "STEP 3: Test P1 Screens"
echo "=============================================="
echo ""
echo "Test each P1 screen with the following actions:"
echo ""

for screen_info in "${P1_SCREENS[@]}"; do
  IFS=':' read -r name path <<< "$screen_info"
  echo "-----------------------------------"
  echo "Screen: $name"
  echo "Path: app/$path"
  echo "-----------------------------------"
  echo ""
  echo "Actions:"
  echo "  1. Navigate to /$name route"
  echo "  2. Observe initial render time (<1s target)"
  echo "  3. Scroll rapidly up and down"
  echo "  4. Monitor FPS counter (should stay at 60 FPS)"
  echo "  5. Check for dropped frames (yellow/red indicators)"
  echo "  6. Test pull-to-refresh (if applicable)"
  echo "  7. Test interactions (taps, swipes)"
  echo ""
  echo "Expected:"
  echo "  - Initial render: <1000ms"
  echo "  - Scrolling FPS: 60 (sustained)"
  echo "  - Dropped frames: <5%"
  echo "  - UI responsiveness: No visible lag"
  echo ""
done

echo "=============================================="
echo "STEP 4: Use React DevTools Profiler (Optional)"
echo "=============================================="
echo ""
echo "For detailed component profiling:"
echo ""
echo "1. Install React DevTools:"
echo "   npm install -g react-devtools"
echo ""
echo "2. Start React DevTools:"
echo "   react-devtools"
echo ""
echo "3. In React Native app:"
echo "   - Shake device → 'Debug with Chrome'"
echo "   - React DevTools should auto-connect"
echo ""
echo "4. Switch to 'Profiler' tab"
echo "5. Click record button"
echo "6. Navigate to screen and perform actions"
echo "7. Stop recording"
echo "8. Analyze flame graph for slow renders"
echo ""
echo "Look for:"
echo "  - Render times >16ms (indicates <60 FPS)"
echo "  - Expensive components (red/orange in flame graph)"
echo "  - Unnecessary re-renders (multiple bars for same component)"
echo ""

echo "=============================================="
echo "STEP 5: Document Results"
echo "=============================================="
echo ""
echo "Create T207-PERFORMANCE-PROFILER-RESULTS.md with:"
echo ""
echo "For each P1 screen:"
echo "  - Initial render time (ms)"
echo "  - Average FPS during scrolling"
echo "  - Dropped frame percentage"
echo "  - Any performance issues found"
echo "  - Screenshots of performance monitor"
echo ""

echo "=============================================="
echo "STEP 6: Verify Success Criteria"
echo "=============================================="
echo ""
echo "SC-006 Requirements:"
echo "  ✓ All screens render in <1 second"
echo "  ✓ 60 FPS maintained during scrolling"
echo "  ✓ No visible lag or jank"
echo "  ✓ Smooth interactions"
echo ""

echo "=============================================="
echo "Expected Outcome"
echo "=============================================="
echo ""
echo "Based on Phase 7 changes:"
echo ""
echo "  - ErrorBoundary: Minimal overhead (~3KB)"
echo "  - ScreenWrapper: Thin wrapper (~5KB)"
echo "  - RNR components: Already optimized"
echo "  - No performance regressions expected"
echo ""
echo "If issues found:"
echo "  1. Profile slow components with React DevTools"
echo "  2. Check for unnecessary re-renders (missing memoization)"
echo "  3. Verify FlatList optimization (if applicable)"
echo "  4. Check for expensive computations in render"
echo ""

echo "=============================================="
echo "Automated Performance Checks"
echo "=============================================="
echo ""
echo "Check if P1 screens have performance monitoring hooks:"
echo ""

cd "$(dirname "$0")/.." || exit 1

for screen_info in "${P1_SCREENS[@]}"; do
  IFS=':' read -r name path <<< "$screen_info"
  
  if [ -f "app/$path" ]; then
    echo "Checking app/$path..."
    
    # Check for performance optimization patterns
    has_memo=$(grep -c "React.memo\|useMemo\|useCallback" "app/$path" 2>/dev/null || echo 0)
    has_flatlist=$(grep -c "FlatList" "app/$path" 2>/dev/null || echo 0)
    has_perf_monitor=$(grep -c "usePerformanceMetrics\|PerformanceMonitor" "app/$path" 2>/dev/null || echo 0)
    
    echo "  - Memoization patterns: $has_memo"
    echo "  - FlatList usage: $has_flatlist"
    echo "  - Performance monitoring: $has_perf_monitor"
    echo ""
  else
    echo "  ⚠️  File not found: app/$path"
    echo ""
  fi
done

echo "=============================================="
echo "Quick Performance Smoke Test"
echo "=============================================="
echo ""
echo "Run these commands to check for obvious issues:"
echo ""
echo "1. Check bundle size (should be <15.75MB):"
echo "   cd /d/quester/client"
echo "   npm run build:android -- --reset-cache"
echo "   ls -lh android/app/build/outputs/apk/release/"
echo ""
echo "2. Check for console.log statements (should be 0 in production):"
echo "   grep -r \"console.log\" app/ --exclude-dir=node_modules | wc -l"
echo ""
echo "3. Check for unoptimized images:"
echo "   find assets/ -name \"*.png\" -o -name \"*.jpg\" | xargs du -sh"
echo ""

echo "=============================================="
echo "T207 Completion Checklist"
echo "=============================================="
echo ""
echo "Before marking T207 complete:"
echo "  [ ] Tested all 4 P1 screens (feed, profile, courses, marketplace)"
echo "  [ ] Documented FPS measurements for each screen"
echo "  [ ] Verified <1s initial render times"
echo "  [ ] Checked for dropped frames during scrolling"
echo "  [ ] Created T207-PERFORMANCE-PROFILER-RESULTS.md"
echo "  [ ] No performance regressions from Phase 7 changes"
echo "  [ ] Screenshots/recordings captured (optional)"
echo ""

echo "=============================================="
echo "Manual Testing Required"
echo "=============================================="
echo ""
echo "⚠️  IMPORTANT: This test CANNOT be fully automated."
echo ""
echo "React Native performance profiling requires:"
echo "  - Physical device or emulator running"
echo "  - Manual interaction (scrolling, tapping)"
echo "  - Visual observation of FPS counter"
echo "  - Real-world usage patterns"
echo ""
echo "Estimated testing time: 2-3 hours"
echo ""
echo "Next step: Follow instructions above to perform manual testing,"
echo "then document results in T207-PERFORMANCE-PROFILER-RESULTS.md"
echo ""

echo "=============================================="
echo "Guide complete. Ready for manual testing."
echo "=============================================="
