// Package middleware provides HTTP middleware for the Quester API.
// 008-api-response-optimization T018-T024, T033-T037: ETag and Last-Modified middleware
package middleware

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/cespare/xxhash/v2"
	"github.com/gofiber/fiber/v2"
)

// ETag configuration constants
const (
	// ContextKeyETagEnabled indicates if ETag should be generated
	ContextKeyETagEnabled = "etagEnabled"

	// ContextKeyWeakETag indicates if weak ETag should be used
	ContextKeyWeakETag = "weakETag"

	// ContextKeyLastModified stores the resource's last modified time
	ContextKeyLastModified = "lastModified"

	// ContextKeyUserIDForETag stores user ID for user-specific ETag hashing
	ContextKeyUserIDForETag = "userIDForETag"
)

// ETagConfig holds configuration for the ETag middleware
type ETagConfig struct {
	// Weak determines if weak ETags (W/"...") should be generated by default
	// FR-007: Use weak ETags for list endpoints
	Weak bool

	// IncludeUserID includes user ID in hash for user-specific responses
	// FR-010: Include user ID in ETag calculation for user-specific responses
	IncludeUserID bool

	// Skipper defines a function to skip middleware
	Skipper func(c *fiber.Ctx) bool
}

// DefaultETagConfig returns the default configuration
func DefaultETagConfig() ETagConfig {
	return ETagConfig{
		Weak:          false,
		IncludeUserID: false,
		Skipper:       nil,
	}
}

// ETag creates middleware that generates ETag headers and handles conditional requests.
// FR-006: Generate ETag header for all cacheable GET responses
// FR-008: Return 304 Not Modified when If-None-Match header matches current ETag
// FR-009: Compute ETag by hashing the serialized JSON response body using xxHash
// FR-016: Include Last-Modified header based on resource updated_at timestamp
// FR-017: Return 304 Not Modified when If-Modified-Since matches and resource unchanged
// FR-018: Prefer ETag validation over Last-Modified when both headers present
//
// This middleware intercepts responses to:
// 1. Generate ETag from response body hash
// 2. Check If-None-Match for conditional requests
// 3. Check If-Modified-Since as fallback
// 4. Return 304 Not Modified if appropriate
func ETag(config ...ETagConfig) fiber.Handler {
	cfg := DefaultETagConfig()
	if len(config) > 0 {
		cfg = config[0]
	}

	return func(c *fiber.Ctx) error {
		// Skip non-GET/HEAD requests
		if c.Method() != fiber.MethodGet && c.Method() != fiber.MethodHead {
			return c.Next()
		}

		// Check skipper
		if cfg.Skipper != nil && cfg.Skipper(c) {
			return c.Next()
		}

		// Get conditional request headers
		ifNoneMatch := c.Get("If-None-Match")
		ifModifiedSince := c.Get("If-Modified-Since")

		// Process the request and capture response
		if err := c.Next(); err != nil {
			return err
		}

		// Only process successful responses
		if c.Response().StatusCode() < 200 || c.Response().StatusCode() >= 300 {
			return nil
		}

		// Get response body
		body := c.Response().Body()
		if len(body) == 0 {
			return nil
		}

		// Check if weak ETag should be used (from context or config)
		weak := cfg.Weak
		if weakOverride, ok := c.Locals(ContextKeyWeakETag).(bool); ok {
			weak = weakOverride
		}

		// Get user ID for ETag hash if configured
		var userID string
		if cfg.IncludeUserID {
			if uid, ok := c.Locals(ContextKeyUserIDForETag).(string); ok {
				userID = uid
			} else if uid, ok := c.Locals("userID").(string); ok {
				userID = uid
			}
		}

		// Generate ETag from response body hash
		etag := generateETag(body, userID, weak)

		// Set ETag header
		c.Set("ETag", etag)

		// Handle Last-Modified header (FR-016)
		var lastModified time.Time
		if lm, ok := c.Locals(ContextKeyLastModified).(time.Time); ok && !lm.IsZero() {
			lastModified = lm
			c.Set("Last-Modified", formatHTTPDate(lastModified))
		}

		// FR-018: Prefer ETag validation over Last-Modified when both present
		if ifNoneMatch != "" {
			// FR-008: Check If-None-Match
			if etagMatches(ifNoneMatch, etag) {
				return send304(c)
			}
		} else if ifModifiedSince != "" && !lastModified.IsZero() {
			// FR-017: Fall back to If-Modified-Since only if no If-None-Match
			if notModifiedSince(ifModifiedSince, lastModified) {
				return send304(c)
			}
		}

		return nil
	}
}

// generateETag creates an ETag from response body using xxHash.
// FR-009: Compute ETag by hashing the serialized JSON response body
// FR-010: Include user ID in ETag calculation for user-specific responses
func generateETag(body []byte, userID string, weak bool) string {
	h := xxhash.New()

	// Include user ID in hash for user-specific responses
	if userID != "" {
		h.Write([]byte(userID))
		h.Write([]byte(":"))
	}

	h.Write(body)
	hash := h.Sum64()

	// Format as hex string
	hashStr := strconv.FormatUint(hash, 16)

	// FR-007: Use weak ETags for list endpoints
	if weak {
		return fmt.Sprintf(`W/"%s"`, hashStr)
	}
	return fmt.Sprintf(`"%s"`, hashStr)
}

// etagMatches checks if the If-None-Match header matches the current ETag.
// Handles multiple ETags in header (comma-separated) and wildcard "*"
func etagMatches(ifNoneMatch, currentETag string) bool {
	// Handle wildcard
	if strings.TrimSpace(ifNoneMatch) == "*" {
		return true
	}

	// Normalize current ETag (remove weak prefix for comparison)
	currentStrong := strings.TrimPrefix(currentETag, "W/")

	// Parse multiple ETags
	etags := strings.Split(ifNoneMatch, ",")
	for _, etag := range etags {
		etag = strings.TrimSpace(etag)

		// Normalize for comparison
		etagStrong := strings.TrimPrefix(etag, "W/")

		// Weak comparison (RFC 7232): compare entity-tag values
		if etagStrong == currentStrong {
			return true
		}
	}

	return false
}

// notModifiedSince checks if resource hasn't been modified since given time.
// FR-017: Return 304 Not Modified when If-Modified-Since matches
func notModifiedSince(ifModifiedSince string, lastModified time.Time) bool {
	// Parse If-Modified-Since header (RFC 7231 format)
	since, err := parseHTTPDate(ifModifiedSince)
	if err != nil {
		return false
	}

	// HTTP dates are only accurate to the second
	// Resource is not modified if last modification is at or before the If-Modified-Since time
	return !lastModified.Truncate(time.Second).After(since.Truncate(time.Second))
}

// send304 sends a 304 Not Modified response
func send304(c *fiber.Ctx) error {
	// Clear response body for 304
	c.Response().ResetBody()
	c.Status(fiber.StatusNotModified)
	return nil
}

// formatHTTPDate formats time in RFC 7231 format for HTTP headers.
// Example: "Tue, 15 Nov 1994 08:12:31 GMT"
func formatHTTPDate(t time.Time) string {
	return t.UTC().Format(time.RFC1123)
}

// parseHTTPDate parses time from various HTTP date formats.
// Supports RFC 7231 (preferred), RFC 850 (obsolete), and ANSI C asctime()
func parseHTTPDate(s string) (time.Time, error) {
	// Try RFC 7231 format first (preferred)
	if t, err := time.Parse(time.RFC1123, s); err == nil {
		return t, nil
	}
	// Try RFC 1123Z (with numeric timezone)
	if t, err := time.Parse(time.RFC1123Z, s); err == nil {
		return t, nil
	}
	// Try RFC 850 (obsolete but still accepted)
	if t, err := time.Parse(time.RFC850, s); err == nil {
		return t, nil
	}
	// Try ANSI C asctime() format
	if t, err := time.Parse(time.ANSIC, s); err == nil {
		return t, nil
	}
	return time.Time{}, fmt.Errorf("unable to parse HTTP date: %s", s)
}

// SetLastModified sets the Last-Modified time in context for ETag middleware.
// Call this from handlers to provide resource modification time.
func SetLastModified(c *fiber.Ctx, t time.Time) {
	c.Locals(ContextKeyLastModified, t)
}

// SetWeakETag marks that a weak ETag should be used for this response.
// Call this from list endpoint handlers.
func SetWeakETag(c *fiber.Ctx, weak bool) {
	c.Locals(ContextKeyWeakETag, weak)
}

// SetUserIDForETag sets the user ID to include in ETag hash.
// Call this for user-specific responses.
func SetUserIDForETag(c *fiber.Ctx, userID string) {
	c.Locals(ContextKeyUserIDForETag, userID)
}

// ETagResponseWriter wraps response writing to capture body for ETag generation.
// This is used when ETag middleware needs to process response after handler completes.
type ETagResponseWriter struct {
	Buffer *bytes.Buffer
}

// NewETagResponseWriter creates a new response writer
func NewETagResponseWriter() *ETagResponseWriter {
	return &ETagResponseWriter{
		Buffer: bytes.NewBuffer(nil),
	}
}

// Write captures response body
func (w *ETagResponseWriter) Write(p []byte) (int, error) {
	return w.Buffer.Write(p)
}

// Bytes returns the captured response body
func (w *ETagResponseWriter) Bytes() []byte {
	return w.Buffer.Bytes()
}
