-- T207: Create encryption_keys table
-- Migration: 20250102_create_encryption_keys.sql
-- Purpose: Store Data Encryption Keys (DEKs) encrypted by KMS Key Encryption Keys (KEKs)

CREATE TABLE encryption_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key_id VARCHAR(255) UNIQUE NOT NULL,
    version INT NOT NULL DEFAULT 1,
    encrypted_dek BYTEA NOT NULL,
    algorithm VARCHAR(50) NOT NULL DEFAULT 'AES-256-GCM',
    kms_provider VARCHAR(50) NOT NULL DEFAULT 'aws',
    kms_key_arn TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    rotated_at TIMESTAMP,
    expires_at TIMESTAMP,
    tenant_id UUID,
    
    -- Constraints
    CONSTRAINT chk_status CHECK (status IN ('active', 'rotated', 'expired', 'revoked')),
    CONSTRAINT chk_algorithm CHECK (algorithm IN ('AES-256-GCM', 'AES-128-GCM')),
    CONSTRAINT chk_kms_provider CHECK (kms_provider IN ('aws', 'gcp', 'vault', 'mock'))
);

-- Indexes
CREATE INDEX idx_encryption_keys_key_id ON encryption_keys(key_id);
CREATE INDEX idx_encryption_keys_version ON encryption_keys(version);
CREATE INDEX idx_encryption_keys_status ON encryption_keys(status);
CREATE INDEX idx_encryption_keys_tenant_id ON encryption_keys(tenant_id);
CREATE INDEX idx_encryption_keys_created_at ON encryption_keys(created_at);
CREATE INDEX idx_encryption_keys_rotated_at ON encryption_keys(rotated_at);

-- Unique constraint for version tracking
CREATE UNIQUE INDEX idx_encryption_keys_version_unique ON encryption_keys(version) WHERE status = 'active';

-- Comments
COMMENT ON TABLE encryption_keys IS 'Stores Data Encryption Keys (DEKs) encrypted by KMS Key Encryption Keys (KEKs)';
COMMENT ON COLUMN encryption_keys.key_id IS 'Unique identifier for this DEK (e.g., "dek-2025-001")';
COMMENT ON COLUMN encryption_keys.version IS 'Version number for key rotation (increments on rotation)';
COMMENT ON COLUMN encryption_keys.encrypted_dek IS 'DEK encrypted by KMS KEK (envelope encryption)';
COMMENT ON COLUMN encryption_keys.algorithm IS 'Encryption algorithm for DEK usage';
COMMENT ON COLUMN encryption_keys.kms_provider IS 'KMS provider (aws, gcp, vault)';
COMMENT ON COLUMN encryption_keys.kms_key_arn IS 'KMS Key ARN/ID used to encrypt this DEK';
COMMENT ON COLUMN encryption_keys.status IS 'Key status: active (current), rotated (old but valid), expired, revoked';
COMMENT ON COLUMN encryption_keys.rotated_at IS 'Timestamp when key was rotated (moved from active to rotated)';
COMMENT ON COLUMN encryption_keys.expires_at IS 'Expiration timestamp for key (typically rotated_at + 90 days)';
COMMENT ON COLUMN encryption_keys.tenant_id IS 'Tenant ID for multi-tenant key isolation (nullable for global keys)';

-- Insert initial DEK (will be generated by KMS on first run)
-- This is a placeholder record - actual DEK will be generated by GenerateDataKey()
INSERT INTO encryption_keys (
    key_id, 
    version, 
    encrypted_dek, 
    algorithm, 
    kms_provider, 
    kms_key_arn, 
    status
) VALUES (
    'dek-initial-placeholder',
    1,
    decode('00', 'hex'), -- Placeholder, will be replaced by actual DEK
    'AES-256-GCM',
    'mock',
    'arn:aws:kms:us-west-2:123456789012:key/placeholder',
    'active'
);
